blank_issues_enabled: false
contact_links:
  - name: Wiki
    url: https://github.com/luc-github/ESP3D-WEBUI/wiki
    about: The Wiki has lot of informations.
  - name: Discord chat
    url: https://discord.gg/Z4ujTwE
    about: Join the discord for support and discussion.
